version: "3.7"

networks:
  web:
    external: true

services:
  caddy:
    image: caddy:2.11.2-alpine@sha256:24d58e24e4231c6667677a39469a3d843a3222eadbf640f22933f24bed0939ec
    container_name: caddy
    restart: always
    command: caddy run --watch --config /etc/caddy/Caddyfile --adapter caddyfile 
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    volumes:
      - /home/ubuntu/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /home/ubuntu/caddy/config:/etc/caddy/config:ro
      - /home/ubuntu/caddy/static:/srv/static:ro
      - /home/ubuntu/caddy/proxy_error_page.html:/srv/proxy_error_page.html:ro
      - data:/data
      - config:/config
      - piped-proxy:/var/run/ytproxy
    networks:
      web:

volumes:
  data:
  config:
  piped-proxy:
    external: true
