version: '3.3'

networks:
  web:
    external: true

services:
  element:
    image: vectorim/element-web:v1.12.12@sha256:3f031bba174a062d21dcb506662031ce717586c05c03d018063c19470941ac70
    container_name: element
    restart: unless-stopped
    # ports:
    # - 8002:80
    configs:
      - source: element
        target: /app/config.json
    networks:
      web:

configs:
  element:
    file: /home/ubuntu/element/config.json