version: '3.3'

networks:
  web:
    external: true

services:
  element:
    image: vectorim/element-web:v1.12.11@sha256:f6b3ce26c42804f39afc40fe0ba14d95ab4c41e55e7343ebf6972e042b41f031
    container_name: element
    restart: unless-stopped
    # ports:
    # - 8002:80
    configs:
      - source: element
        target: /app/config.json
    networks:
      web:

configs:
  element:
    file: /home/ubuntu/element/config.json