version: '3.3'

networks:
  web:
    external: true

services:
  element:
    image: vectorim/element-web:v1.12.14@sha256:13052614150733892ff06189f0f9baf098bc16092bffc0e0e18ccf2f257abe34
    container_name: element
    restart: unless-stopped
    # ports:
    # - 8002:80
    configs:
      - source: element
        target: /app/config.json
    networks:
      web:

configs:
  element:
    file: /home/ubuntu/element/config.json