networks:
  web:
    external: true
  default:
    enable_ipv6: true

services:
  redlib:
    container_name: redlib
    image: quay.io/redlib/redlib:latest@sha256:25dbb5466ebd22e58277d4aa54897899b044f02f7219ca3054784aecc0be34e1
    restart: always
    environment:
      - REDLIB_ROBOTS_DISABLE_INDEXING=on
      - REDLIB_DEFAULT_USE_HLS=on
    networks:
      - default

  anubis:
    container_name: anubis-redlib
    image: ghcr.io/techarohq/anubis:latest@sha256:90eb7eab65b28e63bf11f9dedf4b34d599bcaab9d84e8f3d537f027f9ac96c62
    environment:
      BIND: ":8923"
      DIFFICULTY: "3"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "false"
      TARGET: "http://redlib:8080"
    volumes:
      - /home/ubuntu/anubis/botPolicy.json:/data/cfg/botPolicy.json:ro
    user: "1000:1000"
    restart: always
    networks:
      - web
      - default
    depends_on:
      - redlib
