networks:
  web:
    external: true
  default:
    enable_ipv6: true

services:
  redlib:
    container_name: redlib
    image: quay.io/redlib/redlib:latest@sha256:3908c592bba4a17d32516277504c42284600bd826cf1c1f9a309fdedc7bdd27a
    restart: always
    environment:
      - REDLIB_ROBOTS_DISABLE_INDEXING=on
      - REDLIB_DEFAULT_USE_HLS=on
    networks:
      - default

  anubis:
    container_name: anubis-redlib
    image: ghcr.io/techarohq/anubis:latest@sha256:3b1521130264e9c26a70ef91f3a2cf0cdabd87f8bc4564c43bd370e10082edb9
    environment:
      BIND: ":8923"
      DIFFICULTY: "3"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "false"
      TARGET: "http://redlib:8080"
    volumes:
      - /home/ubuntu/anubis/botPolicy.json:/data/cfg/botPolicy.json:ro
    user: "1000:1000"
    restart: always
    networks:
      - web
      - default
    depends_on:
      - redlib
